CREATE TABLE tags(
id INT NOT NULL AUTO_INCREMENT,
class VARCHAR(40) DEFAULT 'Z_Element' NOT NULL,
created_time VARCHAR(255) DEFAULT '0' NOT NULL,
tag VARCHAR(255) NOT NULL,
count INT DEFAULT '1' NOT NULL,
PRIMARY KEY(id)
)
