CREATE TABLE widgets(
id INT NOT NULL AUTO_INCREMENT,
class VARCHAR(40) DEFAULT 'Z_BbCodeElement' NOT NULL,
created_time VARCHAR(255) DEFAULT '0' NOT NULL,
title VARCHAR(255) NOT NULL,
text VARCHAR(1024) NOT NULL,
PRIMARY KEY(id)
)
